### ISSUE TITLE
Latest playtesting results:

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#103]
- [x] 1) Fuck turrets forever. Blanket remove for now, figure out something else later. Seriously.
- [ ] 2) We need a tooltip. Even I don't know what half these Mechs do. 
- [x] 3) Vehicles need healthbars since we can't even mouse over them. 
- [x] 4) If a unit has already chosen all available perks, remove the white perk star from showing up on its UI.
- [ ] 5) Units don't seem to have a healthbar on their infocard? They should.
- [x] 6) Dropship anims need to be much faster, they're annoying waiting for so long.
- [x] 7) IMHO we need blanket radar range decrease by 25-50%.
- [ ] 8) Any way to make LOS sectors affect the LOS viewmode (toggled with L ingame)?
- [ ] 9) I have an idea about dropships.

**Comment by FLOZi** [comment]
1) Can do but I'd rather try doubling the price again first

2) Calling all gajop. I can add weapons to current description as a stopgap.

3) Should be easy

4) Ditto

5) Pretty sure they do?

6) Disagree (partially because its a pita to change)

7) Ok with that, perhaps a modoption for testing

8) Yes. You go learn GLSL and how to use FBOs and report back.

9) Go on...

**Comment by gajop** [comment]
2) @GoogleFrog implemented a nice tooltip widget for Chubby, and although it could use a bit more work so it works with arbitrary tooltips, it looks nice  https://github.com/Spring-Chobby/Chobby/wiki/Additional-Chili-Classnames#overlay_window I plan to use something like this for MCL
