### ISSUE TITLE
unit_beaconbuild.lua crash

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#113]
Speccing an AI game, the following crash occurs when AI attempt to build at a beacon:

[f=0002214] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_beaconbuild.lua"]:212: table index is nil
stack traceback:
	[string "LuaRules/Gadgets/unit_beaconbuild.lua"]:212: in function '?'
	[string "LuaRules/Gadgets/api_delay.lua"]:57: in function 'GameFrame'
	[string "luagadgets/gadgets.lua"]:877: in function <[string "luagadgets/gadgets.lua"]:875>
	(tail call): ?

Followed a couple seconds later by:

[f=0002636] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_beaconbuild.lua"]:212: table index is nil
stack traceback:
	[string "LuaRules/Gadgets/unit_beaconbuild.lua"]:212: in function '?'
	[string "LuaRules/Gadgets/api_delay.lua"]:57: in function 'GameFrame'
	[string "luagadgets/gadgets.lua"]:877: in function <[string "luagadgets/gadgets.lua"]:875>
	(tail call): ?

**Comment by zverofaust** [comment]
Not fixed.

**Comment by FLOZi** [comment]
I did test you cockwomble. I thought that I had determined that it was due to losing a beacon during the order process (I definitely did fix one possible crash there.) Ran several test games without error.

/give ing outposts can screw things marjorly since multiple upgrades & air traffic control as they are intimately tied to the parent beacon.
