### ISSUE TITLE
Dropship cooldown

### ISSUE THREAD

**Issue by gajop** [SpringMCLegacy/SpringMCLegacy#83]
Is the current way dropship cool down works intended? I find it rather weird that a 30s cooldown happens after reinforcements arrive. It's rather unlikely you'll have resources to order another drop so soon anyway amd I'm not sure what's the point gameplay wise.

It would make a lot more sense if it happens when you call for reinforcements and before they arrive. Is this a bug or is it intentional?

**Comment by FLOZi** [comment]
Intentional. There used to also be a pause between submit order and dropship entering playfield, but that was nuked for a couple of reasons. May be reintroduced. Possibly the current delay is insufficient, but it. e.g. prevents just spamming light mechs to deliver your disco-balling death sphere wherever you want it.

**Comment by gajop** [comment]
I see. I guess I found it rather confusing because of the way it was said: "Reinforcements inbound. Estimated time of revival 30s", seeing as they have already arrived.
Maybe it would be better to have the same delay before and after the dropship comes but I feel that's a minor thing if voice was fixed.

**Comment by FLOZi** [comment]
Closing this for now, we could do with a better sound along the lines of "Dropship refuelling, ready in X seconds", but the likelihood is we won't get it until / unless we find a new sound artist.
